---
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      nodeSelector:
        kubernetes.io/hostname: mario
      volumes:
        - name: ha-storage
          hostPath:
            path: "/srv/share/backed/appdata/homeassistant/config/"
            type: Directory
        - name: psql-tls-secrets
          secret:
            secretName: psql-client-secret
            optional: true
            defaultMode: 0640
      containers:
        - image: homeassistant/home-assistant:2023.4
          name: home-assistant
          volumeMounts:
            - mountPath: "/config"
              name: ha-storage
            - name: psql-tls-secrets
              mountPath: "/psql-tls-secrets"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /manifest.json
              port: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      name: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: homeassistant
spec:
  gateways: [istio-system/gateway]
  hosts: [homeassistant.local.ongy.net]
  http:
  - route:
    - destination:
        host: homeassistant.homeassistant.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
      ports:
        - protocol: TCP
          port: 8123
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: psql-client-secret
  namespace: homeassistant
spec:
  isCA: false
  duration: 8760h # 1 years
  commonName: homeassistant
  secretName: psql-client-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: psql-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
