---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      volumes:
        - name: jellyfin-config
          hostPath:
            path: "/srv/share/backed/appdata/jellyfin/"
            type: Directory
        - name: media-data
          hostPath:
            path: "/srv/share/media/"
            type: Directory
      containers:
        - image: cr.hotio.dev/hotio/jellyfin:latest
          env:
          - name: PUID
            value: "1000"
          - name: GUID
            value: "1004"
          - name: UMASK
            value: "002"
          securityContext:
            privileged: true
          readinessProbe:
            httpGet:
              path: /health
              port: 8096
          name: jellyfin
          volumeMounts:
            - mountPath: "/config"
              name: jellyfin-config
            - mountPath: "/data"
              name: media-data
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 8096
      name: http
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: jellyfin
spec:
  gateways: [istio-system/gateway]
  hosts: [jellyfin.local.ongy.net]
  http:
  - route:
    - destination:
        host: jellyfin.jellyfin.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  policyTypes:
    - Ingress
#    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: jellyfin
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: homeassistant
      ports:
        - protocol: TCP
          port: 8096
#  egress:
#    # generally allow traffic inside the namespace
#    - from:
#        - namespaceSelector:
#            matchLabels:
#              kubernetes.io/metadata.name: jellyfin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: jellyfin-mpv
  name: jellyfin-mpv
  namespace: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin-mpv
  template:
    metadata:
      labels:
        app: jellyfin-mpv
    spec:
      nodeSelector:
        graphics: wayland
      volumes:
        - name: user-run
          hostPath:
            path: "/run/user/1000/"
            type: Directory
        - name: config-home
          hostPath:
            path: "/home/ongy/.config/jellyfin-mpv-shim/"
            type: Directory
        - name: x11-unix
          hostPath:
            path: "/tmp/.X11-unix/"
            type: Directory
      containers:
        - image: ongy.net/jellyfin-mpv-shim:alpha1
#        - image: alpine
#          command: ["sleep"]
#          args: ["infinity"]
          imagePullPolicy: Never
          env:
          - name: XDG_RUNTIME_DIR
            value: "/run/user/1000/"
          - name: WAYLAND_DISPLAY
            value: "invalid"
          - name: DISPLAY
            value: ":0"
          securityContext:
            privileged: true
          name: jellyfin-mpv
          volumeMounts:
            - mountPath: "/run/user/1000"
              name: user-run
            - mountPath: "/home/jellyfin/.config/jellyfin-mpv-shim"
              name: config-home
            - mountPath: "/tmp/.X11-unix/"
              name: x11-unix
