---
apiVersion: v1
kind: Namespace
metadata:
  name: psql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: psql
  name: psql
  namespace: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      nodeSelector:
        kubernetes.io/hostname: mario
      volumes:
        - name: psql-data
          hostPath:
            path: "/default/database/pg"
            type: Directory
        - name: psql-wal
          hostPath:
            path: "/default/database/pg_wal"
            type: Directory
        - name: psql-tls-secrets
          secret:
            secretName: psql-server-secret
            optional: true
            defaultMode: 0640
      securityContext:
        fsGroup: 70
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - image: postgres:14-alpine
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
          env:
          - name: POSTGRES_PASSWORD
            value: password
          name: psql
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: psql-data
            - mountPath: "/wal"
              name: psql-wal
            - name: psql-tls-secrets
              mountPath: "/tls-secrets"
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: psql
  namespace: psql
spec:
  selector:
    app: psql
  ports:
    - protocol: TCP
      port: 5432
      name: postgress
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: psql-server-secret
  namespace: psql
spec:
  isCA: true
  duration: 8760h # 1 years
  commonName: psql.psql
  secretName: psql-server-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: psql-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
