# WIP configuration. Not in use yet
---
apiVersion: v1
kind: Namespace
metadata:
  name: syncthing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      volumes:
        - name: syncthing-config
          nfs:
            path: /srv/share/backed/appdata/syncthing/
            server: mario.local.ongy.net
            readOnly: false
        - name: media-data
          nfs:
            path: /srv/share/backed/appdata/photoprism/import/syncthing/
            server: mario.local.ongy.net
            readOnly: false
      containers:
        - image: syncthing/syncthing:latest
          readinessProbe:
            httpGet:
              path: /
              port: 8384
          name: syncthing
          volumeMounts:
            - mountPath: "/var/syncthing"
              name: syncthing-config
            - mountPath: "/data/photoprism/phone"
              name: media-data
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-http
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - protocol: TCP
      port: 8384
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: syncthing-sync
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - protocol: UDP
      port: 22000
      name: udp
    - protocol: TCP
      port: 22000
      name: tcp
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: syncthing
spec:
  gateways: [istio-system/gateway]
  hosts: [syncthing.local.ongy.net]
  http:
  - route:
    - destination:
        host: syncthing-http.syncthing.svc.cluster.local
---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: syncthing
#   namespace: syncthing
# spec:
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#     - from:
#         - namespaceSelector:
#             matchLabels:
#               kubernetes.io/metadata.name: istio-system
#       ports:
#         - protocol: TCP
#           port: 8384
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: syncthing-proxy
  name: syncthing-proxy
  namespace: syncthing
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: syncthing-proxy
  template:
    metadata:
      labels:
        app: syncthing-proxy
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - image: alpine/socat
          name: tcp-proxy
          args:
          - TCP6-LISTEN:22000,reuseaddr,fork
          - TCP:syncthing-sync:22000
        - image: alpine/socat
          name: udp-proxy
          args:
          - UDP6-LISTEN:22000,reuseaddr,fork
          - UDP:syncthing-sync:22000