apiVersion: v1
kind: Namespace
metadata:
  name: vuln-scanning
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trivy-scan-influx-NAME-DATE
  namespace: vuln-scanning
spec:
  template:
    spec:
      volumes:
        - name: output-data
          nfs:
            path: /srv/share/backed/appdata/vuln-scans
            server: mario.local.ongy.net
            readOnly: false
      containers:
        - image: cr.local.ongy.net/ongy/vuln-checker:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "2"
            limits:
              memory: "512Mi"
              cpu: "2"
          name: scanner
          command:
          - /vuln-checker
          args:
          - SCAN-TARGET
          volumeMounts:
            - mountPath: "/output"
              name: output-data
      restartPolicy: OnFailure
