FROM alpine

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip && pip3 install --no-cache --upgrade radicale

WORKDIR /

ENTRYPOINT [ "/usr/bin/radicale" ]
