apiVersion: batch/v1
kind: CronJob
metadata:
  name: ytdl-sub
  namespace: mediaretriever
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: tmp-dir
            emptyDir:
              medium: Memory
              sizeLimit: 500Mi
          - name: ytdl-config
            configMap:
              name: ytdl-config-v1
          - name: media-data
            nfs:
              path: /srv/share/media/youtube
              server: mario.local.ongy.net
              readOnly: false
          containers:
          - name: ytdl
            env:
            - name: PUID
              value: "1006"
            - name: GUID
              value: "1004"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Berlin"
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
            image: ghcr.io/jmbannon/ytdl-sub:latest
            imagePullPolicy: Always
            command:
            - ytdl-sub
            - sub
            - --config
            - /config/config.yaml
            - --subscription-paths
            - /config/subscriptions.yaml
            workingDir: "/tmp"
            volumeMounts:
            - mountPath: "/config"
              name: ytdl-config
            - mountPath: "/tv_shows"
              name: media-data
            - mountPath: "/tmp/"
              name: tmp-dir
          restartPolicy: OnFailure
